version: '3'

services:
  backendserver:
    build: ./housie-service/
    ports:
           - "8080:8080"
    restart: always
  frontend:
    build: ./housie-app/
    links:
           - "backendserver"
    depends_on:
           - "backendserver"
    ports:
           - "80:80"   

